version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    maxBytes: 10000
    backupCount: 1
    formatter: simple
    filename:  /home/pi/lights/server/logs/lights.log
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:

  lights:
    level: DEBUG
    handlers: [file]
    propagate: no

  motion:
    level: DEBUG
    handlers: [ file]
    propagate: no

root:
  level: DEBUG
  handlers: [file]

disable_existing_loggers: False